### ISSUE TITLE
Monkey patching causing parse error in Doctrine Proxies

### ISSUE THREAD

**Issue by Tiriel** [kahlan/kahlan#212] opened 2017-01-04 14:39 UTC
Hey guys!

Just ran into this error while playing with Kahlan on Symfony:

> PHP Parse error:  syntax error, unexpected '$__KMONKEY__1349' (T_VARIABLE), expecting identifier (T_STRING) in /data/www/project/app/cache/dev/doctrine/orm/Proxies/__CG__ProjectAppBundleEntityUsergroup.php on line 47

The beginning of the file itself (with line 47 marked out):
```php
<?php

namespace Proxies\__CG__\Project\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usergroup extends \Project\AppBundle\Entity\Usergroup implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function $__KMONKEY__1349($initializer = null, $cloner = null)   // LINE 47
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }
```

It does not seem to originate from my code directly.
I was creating tests for a controller and so building a Video entity, in which I tried to inject a User entity, itself containing the Usergroup entity. The thing is, I just reused a code from a previous test for a service, which was perfectly working.

To add a bit more to the bizarre, the Usergroup entity is eager fetched by Doctrine (defined in mapping), so I can't see why the Proxy should be built.
And what's more, I'm not trying to patch proxies in any test.

Am I doing something wrong, or is Kahlan trying to monkey patch a method it shouldn't?

**Comment by jails** [comment] 2017-01-04 14:51
Interesting, indeed Kahlan is patching everything by default. If you don't really need to bother with proxies you can exclude them in your `kahlan-config.php` like so
<?php
use Kahlan\Filter\Filter;

Filter::register('exclude.namespaces', function ($chain) {
    $defaults = ['Proxies'];
    $excluded = $this->args()->get('exclude');
    $this->args()->set('exclude', array_unique(array_merge($excluded, $defaults)));
    return $chain->next();
});

Filter::apply($this, 'interceptor', 'exclude.namespaces');
?>

However I'm really interested to see the whole source file to understand why `__construct` as been rewrote `$__KMONKEY__1349`. Looks like there's a glitch in the parser.

**Comment by Tiriel** [comment] 2017-01-04 14:53
Which file do you want to see? The whole proxy or the test file? The test file may be a problem, since it contains proprietary names and specs related to my workplace.

**Comment by jails** [comment] 2017-01-04 14:55
The generated proxy source (i.e. the one responsible from the above kahlan parser output)

**Comment by jails** [comment] 2017-01-04 15:09
@Tiriel nevermind, I was able to reproduce the issue, will keep you posted

**Comment by Tiriel** [comment] 2017-01-04 15:10
Okay, as you wish! I was rebuilding my Docker containers (had trashed them to start fresh), sorry for the delay. Have an idea where it comes from?

**Comment by jails** [comment] 2017-01-04 15:28
Yup, but I'm not sure how to fix it. Doctrine dynamic proxies are genenrated by the `ProxyGenerator` class which uses a couple of heredoc notation to store some code inside.

The problem is not really the heredoc notation since the Kahlan parser is supposed to parse it correctly and ignore strings content from parsing.

The problem rely on the heredoc notation used by Doctrine. According to the [PHP documentation](http://php.net/manual/fr/language.types.string.php), the heredoc notation is:

```php
<?php
<<<EOT
bar
EOT;
```
But looks like Doctrine is using an undocumented way to build their heredocs https://github.com/doctrine/common/blob/master/lib/Doctrine/Common/Proxy/ProxyGenerator.php#L379-L387

And this notation broke the Kahlan parser which simply ignore the heredoc.

And at this point I don't know if I can/should handle.

**Comment by jails** [comment] 2017-01-04 15:45
Ok it should be fixed by https://github.com/kahlan/kahlan/commit/e3678f3815b159e18349d16e3b6806049391bb7c
@Tiriel clear up your `/tmp/kahlan` cache files and the dev branch should solve your issue.

**Comment by Tiriel** [comment] 2017-01-04 15:46
It would seem the notation used by Doctrine is more Nowdoc than Heredoc, their use seems documented, though I had rarely seen it used.
http://php.net/manual/fr/language.types.string.php#language.types.string.syntax.nowdoc

I don't know if it's possible for you to handle it, and if you should too indeed. Maybe this is something I can implement in the KahlanBundle for Symfony though? I think it will depend on the number of devs using Doctrine outside Symfony.

**Comment by Tiriel** [comment] 2017-01-04 15:46
Too quick for me! Thanks anyway, I'll composer-update then.

**Comment by jails** [comment] 2017-01-04 15:51
Ah interesting, didn't know about that one, thank you for the head up :+1:

**Closed** 2017-01-04 16:44 UTC
