### ISSUE TITLE
Feature request: description of mismatch

### ISSUE THREAD

**Issue by agrrr3** [kahlan/kahlan#288] opened 2017-11-27 15:02 UTC
If a test fails, sometimes it would be handy to have the exact difference between the expected and the actual result reported.
I think this is not possible at the moment with kahlan. Please correct me if i am wrong.

If it doesnt exist maybe i would like to implement that functionality. 
I need a hint where to start and or if there is another way to add diffing. 

I know from groovy and java two general approaches to do this:
* add a describeMismatch method to every matcher (so the matcher knows what to look for and adds to  a composable description)
* use a generic diffing between parameters (like in groovy power asserts)

The power asserts from groovy are the best, because they give you a complete report on all statements used and are not even tied to testing:
```Assertion failed: 
assert 91 == a * b
          |  | | |
          |  10| 9
          |    90
          false
```
i dont think that will be possible even with monkeypatching or similar with php

so the next best is given a useful difference information between actual and expected result for the  e.g. when matching strings for equality
```
Expected: The small brown fox jumps over the lazy dog
                                    ^                                                           
  Actual: The small brown fox jumps some hops
```

So, repeating myself:
If it doesnt exist maybe i would like to implement that functionality. 
I need a hint where to start and or if there is another way to add diffing.

**Comment by jails** [comment] 2017-11-28 00:28
Hello !
Sure, it would be great if we can provide more information between actual/expected difference.
Afaik PHP doesn't offer such level of variables/objects inspection so I don't think it'll be possible.
However maybe some matcher can be enhanced like `toEqual()` when operated on strings.

**Comment by agrrr3** [comment] 2017-11-28 10:06
So for design decisions:

I think best would be to have access to the diff in the
Reporter#_reportFailure.

Question 1:
* should the difference always be calculated on failure
* or should it be calculated on demand (only if the reporter asks for it)

Question 2:
* should the matcher be responsible for the calculating the difference
(because the matcher has more context information of what is expected)
* or should the difference be a generic difference based on the types of
the actual and expected values (because then the reporter can calculate the
difference without knowing about the matcher)

I would suggest - but maybe thats a no-go - to always calculate the
difference on failure, and store the difference as a value (a string
representation probably at least stringifiable) in the Expectation#_logs in
function Expectation#_log().


2017-11-28 1:28 GMT+01:00 Simon JAILLET <notifications@github.com>:

**Comment by jails** [comment] 2017-12-03 11:55
Right now matchers must implement a `description()` method. This method can return a string or an array when some context is needed at the reporter level.

Simple description: https://github.com/kahlan/kahlan/blob/master/src/Matcher/ToBe.php#L23-L26
Detailed description: https://github.com/kahlan/kahlan/blob/master/src/Matcher/ToBeCloseTo.php#L31-L53

Since the detailed description contain the value of `$actual`, `$expected` the diffing is done right there: https://github.com/kahlan/kahlan/blob/master/src/Reporter/Terminal.php#L336-L374

On top of that, @ezzatron added an additional behavior here. So if the detailed description array is containing a `true` value at the `'external'` key, the "diffing" is delegated the the matcher itself by using its description entry as the "diff" to render https://github.com/kahlan/kahlan/blob/master/src/Reporter/Terminal.php#L294-L311

So I don't really know what should be the best design option at this step. If an helper can be created to generate some kind of generic differences between any kind of data, it would be the best option (from a separation of concern perspective). If it's not possible because of some underlying dependencies, the best option would be the one minimizing them imo.

**Comment by agrrr3** [comment] 2017-12-05 12:37
so if i get this right, Terminal currently only reports a diff if data['external'] is truthy which only happens if there is delegated/callable handler on the expectation. I did not find any occurences outside of the specs. I'm 

So i suggest adding specific diff calculation to the matchers where needed and passing that along using the return array from description under a 'difference' key and use that in the reporter.
If i find a generic diff solution the reporter itself can use it if no difference key is in the array.

If this is not enough, we could think of let the user add a difference function when creating the expectation using a 'differ' config entry (similar to the 'handler').

I think that would cover all bases (the general case, the matcher-context aware and the user specific one).

**Comment by jails** [comment] 2017-12-15 21:44
Not really. There's the internal diff way (the built-in one) and an external way which is available for plugins so they can manage their own diffing.
I'm not sure to get how diffing can be delegated to matchers. Whatever the matcher is, the actual and expected values can be anything. So we need to be able to compare anything with anything at some point imo.

**Comment by ezzatron** [comment] 2017-12-16 00:16
The way I handled similar "diffing" of expected and actual values in Phony was to first "export" each value to a string, and then perform regular string diff on the exported values. Here's an example of what it looks like:

![output](http://eloquent-software.com/phony/master/img/verification.svg)

I chose to use an export format without newlines, and to use a word diff instead of a line diff. This is particularly good for highlighting differences in big strings, where a line diff is pretty useless.

If you choose to take this approach, you first need to write an exporter, which supports all the weirdness of PHP's types, as well as recursive structures etc. etc. I do have a prototype of Phony's exporter extracted into it's own project over at [eloquent/depict](https://github.com/eloquent/depict) if you're interested.

**Comment by agrrr3** [comment] 2017-12-20 12:38
@jails regarding diffing to the matcher: e.g. the  ToBeAnInstanceOf matcher knows that the actual should be of a certain type. For this matcher the difference is "The actual was a string, not an instance of BlubbObject"

**Comment by agrrr3** [comment] 2017-12-20 12:43
@ezzatron yes, i like your approach for normalized export and then fallback to string diffing. So I'm very interested in using depict. Could you point me to the string diffing as well?

**Comment by agrrr3** [comment] 2018-02-20 13:25
An update: I am using \cogpowered\FineDiff for the diffing in peridot in one of my projects.
That has some options for formatting and the way the diff is calculated (e.g. character diff, word diff)

I find that a useful diff often depends on the test and actually also the failure. 

So easy reconfiguration of the diff would also be useful. E.g. diffing in javascript in the html report would be great (but definitly out of scope for me).

**Comment by ezzatron** [comment] 2018-02-20 21:39
@agrrr3 Sorry I missed the question about diffing. At the moment, I haven't abstracted that part of Phony into a component, but I can attempt to explain what I did.

Firstly, I took the [php-diff](https://github.com/chrisboulton/php-diff) source code, and threw out everything except the [SequenceMatcher class](https://github.com/chrisboulton/php-diff/blob/master/lib/Diff/SequenceMatcher.php) which actually implements the core diffing algorithms. From memory, the vanilla code was causing notices/warnings. So I first fixed those issues, then removed what I didn't need, optimized the code as best I could, and made its interface better for my specific use case. The result is Phony's [DifferenceSequenceMatcher class](https://github.com/eloquent/phony/blob/master/src/Difference/DifferenceSequenceMatcher.php).

The Phony difference sequence matcher takes two sequences as arrays, and spits out a set of "opcodes" which describe the difference. But in order to implement a visual string diff on top of this, you need to decide a) how to turn a string into a sequence, and b) how to render the opcodes returned by the sequence matcher back to a string, for display to the user. In Phony, this is done in the [DifferenceEngine class](https://github.com/eloquent/phony/blob/master/src/Difference/DifferenceEngine.php) (it also provides a nicer interface to work with than the sequence matcher).

By changing how you turn the string into a sequence, you can essentially change whether it's a line-based, word-based, or some other more exotic type of diff. Phony uses word diff because the values being diffed are always single line by design. And since it's word diff, I decided to adopt the same difference syntax utilized by existing word diffing tools (`{+addition+}`, `[-removal-]`), which allows tools like `colordiff` to automatically highlight the result.

**Comment by jails** [comment] 2018-03-10 00:47
@agrrr3, since you were able to hack Kahlan to get the report you want, I assume the core were flexible enough to customize the reporting step?
So unless somebody can provide a full featured PR with a better reporting paradigm, I'm closing this for now.

**Closed by jails** 2018-03-10 00:47 UTC
Labels: feature request
