### ISSUE TITLE
Stubing method does not behave as it should

### ISSUE THREAD

**Issue by kamilhurajt** [kahlan/kahlan#226] opened 2017-03-03 10:22 UTC
Hello, in small piece of code for test the stubbing method does not work. 

```
$tracker = new Tracker();
allow($tracker)->toRecieve('getTrackerId')->andReturn(123);

$otherService = new Service($tracker);

$result = $otherService->initProcess();

foreach($result as $job)
{
    expect($job->getTrackId())->toBe(123);
    ......
}
```

Inside of Service class is method process what is calling tracker like this:

```
foreach($allowedProcesses as $processName) {
     $this->jobs[] = new Job($processName, $this->tracker->getTrackerId());
}

return $this->jobs;
```

Issue is that instead of 123 all job's are returning real id: 'uyF44k&7' what is generated in constructor and set in trackerId variable of object. But all implementations are using getTrackerId method what is returning this variable even I mocked this object and method it is not behave as it should

**Comment by jails** [comment] 2017-03-03 10:29
The syntax looks good, can you provide a github repo with a reproductible example ? Looks like the issue is more like related to how everything has been assembled altogether.

**Comment by kamilhurajt** [comment] 2017-03-03 10:36
Hi Jails, cannot provide repo but I can pass you over here whole implementation of file:

```php

use Phalcon\DI\FactoryDefault\CLI;
use W3\Ziipr\QueueWorkers\UserActionsQueueWorker;
use W3\Ziipr\Services\v1\Tracker\Tracker;
use Kahlan\Plugin\Double;

describe("UserActionsQueueWorker", function(){
    $di = CLI::getDefault();
    //mock db connection
    $db = Double::instance([
        'extends'      => \Phalcon\Db\Adapter\Pdo\Mysql::class,
        'magicMethods' => true
    ]);

    allow($db)->toReceive('insert')->andReturn(true);
    allow($db)->toReceive('update')->andReturn(true);
    allow($db)->toReceive('delete')->andReturn(true);
    allow($db)->toReceive('lastInsertId')->andReturn(20);

    $sqs = $di->getShared('queue');
    $user = $di->getShared('users');
    it("->initProcess()", function() use($user, $sqs, $db){

        allow($sqs)->toReceive('useTube', 'put')->andReturn(true);

        $tracker = new Tracker();
        $tracker->setDbConnection($db);

        $worker = new UserActionsQueueWorker($sqs, $user, $tracker);

        $jobs = $worker->initProcess(1);

        foreach($jobs as $job) {
            expect($job->getStatus())->toBe(Tracker::STATUS_PENDING);
            expect($job->getJobId())->toBe(20);
            expect($tracker->getTrackerId())->toBe($tracker->getTrackerId());
        }
    });

});
```

**Comment by m1ome** [comment] 2017-03-03 11:30
@kamilhurajt do you load classes into Kahlan loader?

There is a phalcon Kahlan example in my repos.

**Comment by kamilhurajt** [comment] 2017-03-03 11:32
@m1ome Yes I did, so there is no problem with class loading.

**Comment by jails** [comment] 2017-03-03 11:41
Check that everything is loaded through the composer autoloader (i.e. no "hard-coded" `require/include` statements anywhere) and you didn't add `W3` as excluded namespaces in your `kahlan-config.php`. However with no reproductible repo we can't really help here so I'm closing this.

**Closed by jails** 2017-03-03 11:41 UTC

**Comment by kamilhurajt** [comment] 2017-03-03 13:06
I really don't khow what namespace W3 might cause in this case. But there is PSR-4 autoloading using composer what is included in kahlan-config.php

Here is the config:

```php
use Kahlan\Filter\Filter;
use Kahlan\Reporter\Coverage\Exporter\Coveralls;
use Kahlan\Jit\Interceptor;
use Kahlan\Jit\Patcher\Layer;

date_default_timezone_set('Europe/Paris');
// Define path to application directory
defined('APPLICATION_PATH') || define('APPLICATION_PATH', realpath(dirname(__FILE__)));

$commandLine = $this->commandLine();
$commandLine->option('src', 'default', './');

Filter::register('api.patchers', function($chain) {
    $interceptor = Interceptor::instance();
    $patchers = $interceptor->patchers();
    $patchers->add('layer', new Layer([
        'override' => [
            'Phalcon\Mvc\Model' // apply a layer on top of all classes extending `Phalcon\Mvc\Model`.
        ]
    ]));

    return $chain->next();
});

Filter::apply($this, 'patchers', 'api.patchers');


$tube_name = 'userActions';
// Read configuratio
include(APPLICATION_PATH . '/config/config.php');


// Read auto-loader
include(APPLICATION_PATH . '/config/loader.php');

// Read services
include(APPLICATION_PATH . '/config/services.php');

\Phalcon\Di\FactoryDefault\Cli::setDefault($di);

require(__DIR__ . '/vendor/autoload.php');
```

Here is the test ( it's only one! )

```php
<?php

use Phalcon\DI\FactoryDefault\CLI;
use W3\Ziipr\QueueWorkers\UserActionsQueueWorker;
use W3\Ziipr\Services\v1\Tracker\Tracker;
use Kahlan\Plugin\Double;

/**
 * @Covers UserActionsQueueWorker
 */
describe("W3\\Ziipr\\QueueWorkers\\UserActionsQueueWorker", function(){
    $di = CLI::getDefault();
    //mock db connection
    $db = Double::instance([
        'extends'      => \Phalcon\Db\Adapter\Pdo\Mysql::class,
        'magicMethods' => true
    ]);

    allow($db)->toReceive('insert')->andReturn(true);
    allow($db)->toReceive('update')->andReturn(true);
    allow($db)->toReceive('delete')->andReturn(true);
    allow($db)->toReceive('lastInsertId')->andReturn(20);

    $sqs = $di->getShared('queue');
    $user = $di->getShared('users');

    it("->initProcess()", function() use($user, $sqs, $db){

        allow($sqs)->toReceive('useTube', 'put')->andReturn(true);

        $tracker = new Tracker();
        allow($tracker)->toReceive('getTrackerId')->andReturn(123);
        $tracker->setDbConnection($db);

        $worker = new UserActionsQueueWorker($sqs, $user, $tracker);

        $jobs = $worker->initProcess(1);

        foreach($jobs as $job) {
            expect($job->getStatus())->toBe(Tracker::STATUS_PENDING);
            expect($job->getJobId())->toBe(20);
            expect($tracker->getTrackerId())->toBe(123);
        }
    });

    it("->handle()", function() use($db, $user, $sqs){
        $tracker = new Tracker();
        $tracker->setDbConnection($db);
        $service = new UserActionsQueueWorker($sqs, $user, $tracker);

        expect($service)->toReceive('initProcess')->with(123);

        $jobData = new stdClass();
        $jobData->action = 'USER_DELETE';
        $jobData->user_id = 123;

        $service->handle($jobData);


    });

});
```

There is really nothing more to see, autoloader is generated by composer composer.json is:

`
{
  "require": {
    "ruflin/elastica": "^3.1",
    "pda/pheanstalk": "^3.1",
    "zendframework/zend-mail": "^2.6",
    "guzzlehttp/guzzle": "^6.2",
    "php-http/guzzle6-adapter": "^1.1",
    "sparkpost/sparkpost": "^2.0",
    "aws/aws-sdk-php": "2.8.22.0",
    "ps/image-optimizer": "^1.0",
    "sproutvideo/sproutvideo": "^1.0"
  },
  "require-dev" : {
    "kahlan/kahlan" : "~3.0"
  }
}
`

Is it enough for you to see the problem or you need more ? ( App structure is not important I guess ) but it's:
`
app/ <-- all source files
app/spec/ <--- kahlan tests
app/kahlan-config.php
app/vendor/
`

Just in case of feedback: Thanks for closing, but close the issue with not trying to resolve it or look at the problem what is not so hardly needed to explain a lot for 1 simple test, it will not help users to further use this framework and contribute to the framework. 

Please also update documentation as there is lot of stuff missing ( in case of configuration ).

**Comment by jails** [comment] 2017-03-03 13:30
I know it's quite irritating, but I really can't help without a reproductible repo.

> There is really nothing more to see

Issues always rely where you didn't expect them, so I need something to play with. So if you make the effort to replace your "proprietary code" to some "fake code" so you can publish it somewhere. I'll make the effort to clone it and fix your issue or Kahlan if related.

**Comment by jails** [comment] 2017-03-03 13:34
> Please also update documentation as there is lot of stuff missing ( in case of configuration ).
If you know what are missing stuff open a PR and help other users by opening a PR, it's open source you know.

**Comment by m1ome** [comment] 2017-03-04 07:07
@kamilhurajt I don't see any stuff related to autoloading files in your `kahlan-config.php`

Here is a example: https://github.com/m1ome/kalhan_phalcon/blob/master/kahlan-config.php#L14-L22

**Comment by jails** [comment] 2017-03-04 13:52
Imo @m1ome is right. Seems you are using a custom autoloader while Kahlan only works with Composer.
```
// Read auto-loader
include(APPLICATION_PATH . '/config/loader.php');
```
[More information here](https://kahlan.github.io/docs/integration.html)
