### ISSUE TITLE
Bug: cannot stub method without using 'methods' option

### ISSUE THREAD

**Issue by adamcameron** [kahlan/kahlan#380] opened 2021-03-06 14:25 UTC
I touched on this in https://github.com/kahlan/kahlan/issues/377#issuecomment-791945836, but now have a repro case for it:

```
namespace adamCameron\fullStackExercise\Model;

class SomeClass {
    public function stubMe() {
        return 'real value';
    }
}
```

```
namespace adamCameron\fullStackExercise\spec\unit;

use adamCameron\fullStackExercise\Model\SomeClass;
use Kahlan\Plugin\Double;

describe('Tests of SomeClass', function () {

    it("should be possible to stub a method without using 'methods' option", function () {
        $someObject = new SomeClass();

        expect($someObject->stubMe())->toBe('real value');

        $double = Double::instance(['extends' => SomeClass::class]);
        allow($double)->toReceive('stubMe')->andReturn('stubbed value');

        expect($double->stubMe())->toBe('stubbed value');
    });

    it("works when I use 'methods' option", function () {
        $someObject = new SomeClass();

        expect($someObject->stubMe())->toBe('real value');

        $double = Double::instance(['extends' => SomeClass::class, 'methods'=>['stubMe']]);
        allow($double)->toReceive('stubMe')->andReturn('stubbed value');

        expect($double->stubMe())->toBe('stubbed value');
    });
});
```

Result:

```
F.                                                                  2 / 2 (100%)


Tests of SomeClass
  ✖ it should be possible to stub a method without using 'methods' option
    expect->toBe() failed in `.spec/unit/someClass.spec.php` line 18

    It expect actual to be identical to expected (===).

    actual:
      (string) "real value"
    expected:
      (string) "stubbed value"


Expectations   : 4 Executed
Specifications : 0 Pending, 0 Excluded, 0 Skipped

Passed 1 of 2 FAIL (FAILURE: 1) in 0.076 seconds (using 7MB)

Coverage Summary
----------------

Total: 4.00% (1/25)

Coverage collected in 0.034 seconds
```

As @jails said in that other issue:
> The 'methods' options creates new "virtual method stubs" so you don't need it here.

And the docs suggest the same:
> So allow() on stubs can be applied on any method name. Under the hood __call() will catch everything. You should pay attention that method_exists won't work on this "virtual method stubs". To make it works, you will need to add the necessary "endpoint(s)" using the 'methods' option like in the following example:

`methods` is intended for another purpose, but it seems it's got coupled to the stubbing somehow too.

Lemme know if the code isn't enough to go on. Oh... versions...

```
root@5f9133aa9de3:/usr/share/fullstackExercise# php -v
PHP 8.0.2 (cli) (built: Feb  9 2021 19:20:59) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.2, Copyright (c) Zend Technologies
    with Xdebug v3.0.1, Copyright (c) 2002-2020, by Derick Rethans
root@5f9133aa9de3:/usr/share/fullstackExercise# vendor/bin/kahlan --version
version 5.0.8

For additional help you must use --help

root@5f9133aa9de3:/usr/share/fullstackExercise#
```

**Comment by adamcameron** [comment] 2021-03-07 19:48
See my comment on https://github.com/kahlan/kahlan/issues/377#issuecomment-792340557.

There might be an environmental consideration here that I have not completely locked down. But the problem doesn't occur in all environments.

I'm gonna try to narrow things down a bit and report back.

**Comment by adamcameron** [comment] 2021-03-08 11:36
I've found the cause of this. Repro here: https://github.com/adamcameron/kahlan-issues

**Comment by jails** [comment] 2021-03-08 17:12
Thanks for the detailed example.

Kahlan is adding an extra layer on top of the composer autoloader to be able to perform some Just In Time patching.
In your example `laminas/laminas-code` which is relying on `laminas/laminas-zendframework-bridge` is also adding an extra layer on top of the composer autoloader to be able to automatically aliases some legacy class names](https://github.com/laminas/laminas-zendframework-bridge/blob/1.3.x/src/Autoloader.php#L51-L55).

The problem is that the prepended autoloader is overriding the Kahlan's one.

I'm not sure how to properly solve this issue. The first thing I've in mind is to put the Kahlan's autoloader back in place.
Then for all deprecated class names, if some are still used, I don't see another option that adding them manually.

So as a workaround, adding the following filter in `kahlan-config.php` could be a first step forward. 
```php
use Kahlan\Jit\ClassLoader;

Filters::apply($this, 'bootstrap', function ($next) {
    $loader = ClassLoader::instance();
    $loader->unregister();
    $loader->register(true);

    // Manually aliases deprecated laminas class names if some old names are still used somewhere
    // class_alias('New\Name\Space\ClassName', 'Legacy\Name\Space\ClassName')

    return $next();
});
```

**Comment by adamcameron** [comment] 2021-03-08 18:16
Ah! Given there's autoloader shenanigans going on, could this be the cause of another issue I was seeing [in certain circumstances, let's not worry about what they were for now]:

```
  an uncaught exception has been thrown in `vendor/laminas/laminas-zendframework-bridge/src/Autoloader.php` line 168

    message:`Kahlan\PhpErrorException` Code(0) with message "`E_WARNING` Cannot declare class Zend\\Code\\Generator\\ClassGenerator, because the name is already in use"
```

I mean if both Zend and Kahlan are competing to autoload things?

Superficially, It seemed like something odd Kahlan was doing with autoloading because if I was to run my *PHPUnit* tests first (same test code, different harness), then the Kahlan tests would run fine after that. But if I downed the container and brought it up again, and ran these tests via Kahlan first: got the error above. 

I did not raise this one as there were so many moving parts I could not work out how to give any semblance of a test case for it. But it *is* readily replicable. I can poss work out how to sort out some code to demonstrate it now...

**Comment by jails** [comment] 2021-03-08 22:03
The Kahlan autoloader is just a drop in replacement of the composer autoloader no more no less.
However the LaminasZendframeworkBridge autoloader requires classes to be autoloaded in a very specific way so all `class_alias()` doesn't generate conflicts.
Since there's no way to pass the composer autoloader of your choice as a parameter of the Zend Bridge Autoloader class and all methods are privates (to be sure nobody will be able to reuse their code) I guess you'll have no choice to override this class entirely so you can avoid it to dig up the "real composer directly" an recreate the intended autoloading logic:

```php
<?php
use Kahlan\Filter\Filters;
use Kahlan\Jit\ClassLoader;
use Laminas\ZendFrameworkBridge\RewriteRules;

// Almost a copy paste of https://github.com/laminas/laminas-zendframework-bridge/blob/1.3.x/src/Autoloader.php
class ZendFrameworkBridgeAutoloader
{
    public static function load($classLoader)
    {
        $loaded = new ArrayObject([]);

        spl_autoload_register(self::createPrependAutoloader(
            RewriteRules::namespaceReverse(),
            $classLoader,
            $loaded
        ), true, true);

        spl_autoload_register(self::createAppendAutoloader(
            RewriteRules::namespaceRewrite(),
            $loaded
        ));
    }

    /**
     * @return callable
     */
    private static function createPrependAutoloader(array $namespaces, ClassLoader $classLoader, ArrayObject $loaded)
    {
        /**
         * @param  string $class Class name to autoload
         * @return void
         */
        return static function ($class) use ($namespaces, $classLoader, $loaded) {
            if (isset($loaded[$class])) {
                return;
            }
            $segments = explode('\\', $class);

            $i = 0;
            $check = '';

            while (isset($segments[$i + 1], $namespaces[$check . $segments[$i] . '\\'])) {
                $check .= $segments[$i] . '\\';
                ++$i;
            }

            if ($check === '') {
                return;
            }

            if ($classLoader->loadClass($class)) {
                $legacy = $namespaces[$check]
                    . strtr(substr($class, strlen($check)), [
                        'ApiTools' => 'Apigility',
                        'Mezzio' => 'Expressive',
                        'Laminas' => 'Zend',
                    ]);
                class_alias($class, $legacy);
            }
        };
    }

    /**
     * @return callable
     */
    private static function createAppendAutoloader(array $namespaces, ArrayObject $loaded)
    {
        /**
         * @param  string $class Class name to autoload
         * @return void
         */
        return static function ($class) use ($namespaces, $loaded) {
            $segments = explode('\\', $class);

            if ($segments[0] === 'ZendService' && isset($segments[1])) {
                $segments[0] .= '\\' . $segments[1];
                unset($segments[1]);
                $segments = array_values($segments);
            }

            $i = 0;
            $check = '';

            // We are checking segments of the namespace to match quicker
            while (isset($segments[$i + 1], $namespaces[$check . $segments[$i] . '\\'])) {
                $check .= $segments[$i] . '\\';
                ++$i;
            }

            if ($check === '') {
                return;
            }

            $alias = $namespaces[$check]
                . strtr(substr($class, strlen($check)), [
                    'Apigility' => 'ApiTools',
                    'Expressive' => 'Mezzio',
                    'Zend' => 'Laminas',
                    'AbstractZendServer' => 'AbstractZendServer',
                    'ZendServerDisk' => 'ZendServerDisk',
                    'ZendServerShm' => 'ZendServerShm',
                    'ZendMonitor' => 'ZendMonitor',
                ]);

            $loaded[$alias] = true;
            if (class_exists($alias) || interface_exists($alias) || trait_exists($alias)) {
                class_alias($alias, $class);
            }
        };
    }
}

Filters::apply($this, 'bootstrap', function ($next) {
    $loader = ClassLoader::instance();
    // Starting from scratch and removing all autoloaders
    $functions = spl_autoload_functions();
    foreach($functions as $function) {
        spl_autoload_unregister($function);
    }
    // Register Kahlan first (which is a drop in replacement of Composer)
    $loader->register();
    // Applying Zend Hack to a compatible composer autoloader
    ZendFrameworkBridgeAutoloader::load($loader);
    return $next();
});
```

So this issue is more an incompatibility generated by a customization of the composer autoloader intended to deal with Legacy classes than something which can be fixed in Kahlan's core.

**Comment by adamcameron** [comment] 2021-03-08 22:46
I wonder if there's a way to get rid of all those Zend/Laminas dependencies that Symfony is forcing on me. It's not like I'm using either of them, didn't ask for any compatibility to it, so I really don't know why Symfony is deciding "oh we better clutter things up even more than we already do by adding all this sh*te in as well". However this does seem to be the way Symfony tends to roll.

(that's me thinking out out, rather than asking for input from you!)

I might track back through all the crap Symfony is installing and see if I can coerce it to *not* install it. Then... problem goes away.

Cheers for looking into it!

**Comment by jails** [comment] 2021-04-21 20:15
Closing this issue since this bug is not directly related to the Kahlan codebase.

**Closed by jails** 2021-04-21 20:15 UTC
Labels: invalid
